### PR TITLE
Michael bio: Workflow-group 2

### PR DESCRIPTION
**Pull request by MichaelMugaiga**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [ ] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### CODE REVIEW

**Review by johnedelbi — COMMENTED** [review]
please check npm lint and re-push again

**Comment by johnedelbi** [comment]
Run npm run lint:ls 

and fix the error that you see

**Comment by MichaelMugaiga** [comment]
I have fixed the errors and pushed my work again. you can review and give feedback

**Review by johnedelbi — COMMENTED** [review]
image


samir and tam told us to add just 1 file or the files related to the commit in 1 commit and i see that you add 12 files and 3 of them are not for your bio

**Comment by johnedelbi** [comment]
@MichaelMugaiga This branch has conflicts that must be resolved

**Pull request closed without merging**
